name: work-1
on:
  push:
    branches:
      - main
jobs:
  hello1:
    runs-on: ubuntu-latest
    steps:
      - name: sayHi
        run: echo "Hi"
      - name: sayMyName
        run: echo "${{ github.actor }}"
  hello2:
    runs-on: ubuntu-latest
    steps:
      - name: sayHiInKorean
        run: echo "안녕하세요"
      - name: checkIpAddresses
        run: ip addr
